#
# Makefile for the LGE board
#

# LGE V3 Model
obj-$(CONFIG_MACH_MSM7X25A_V3) += vee3/

# LGE V7 Model 
obj-$(CONFIG_MACH_MSM8X25_V7) += vee7/

# LGE U0 Model
obj-$(CONFIG_MACH_MSM7X27A_U0) += u0/

# LGE V1 Model 
obj-$(CONFIG_MACH_MSM7X25A_V1) += v1/
